In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv("../datasets/titanic.csv")

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"], inplace=True)

In [17]:
df.shape

(891, 8)

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()

df["Sex"] = le.fit_transform(df["Sex"]).astype(int)

In [20]:
df["Sex"]

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [21]:
df = pd.get_dummies(df, columns=["Embarked"], dtype=np.float64)

In [22]:
df.shape

(891, 10)

In [23]:
df.loc[df.isnull().any(axis=1)]

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
5,0,3,1,NaN,0,0,8.4583,0.0,1.0,0.0
17,1,2,1,NaN,0,0,13.0000,0.0,0.0,1.0
19,1,3,0,NaN,0,0,7.2250,1.0,0.0,0.0
26,0,3,1,NaN,0,0,7.2250,1.0,0.0,0.0
28,1,3,0,NaN,0,0,7.8792,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
859,0,3,1,NaN,0,0,7.2292,1.0,0.0,0.0
863,0,3,0,NaN,8,2,69.5500,0.0,0.0,1.0
868,0,3,1,NaN,0,0,9.5000,0.0,0.0,1.0
878,0,3,1,NaN,0,0,7.8958,0.0,0.0,1.0
888,0,3,0,NaN,1,2,23.4500,0.0,0.0,1.0

In [25]:
df.drop(columns=["Age"], inplace=True)

In [26]:
df.loc[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Survived, Pclass, Sex, SibSp, Parch, Fare, Embarked_C, Embarked_Q, Embarked_S]
Index: []

In [30]:
from sklearn.cluster import MeanShift, estimate_bandwidth

In [35]:

model = MeanShift(
    bandwidth=30,
    n_jobs=4 # ile procesorów ma użyć
)
model.fit(df)

MeanShift(bandwidth=30, n_jobs=4)

In [31]:
estimate_bandwidth(df)

np.float64(20.46398164354367)

In [36]:
model.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 3, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
np.unique(model.labels_)

array([0, 1, 2, 3])

In [39]:
df["cluster_group"] = model.labels_

In [41]:
df.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,cluster_group
0,0,3,1,1,0,7.2500,0.0,0.0,1.0,0
1,1,1,0,1,0,71.2833,1.0,0.0,0.0,0
2,1,3,0,0,0,7.9250,0.0,0.0,1.0,0
3,1,1,0,1,0,53.1000,0.0,0.0,1.0,0
4,0,3,1,0,0,8.0500,0.0,0.0,1.0,0

In [42]:
df["cluster_group"].value_counts()

cluster_group
0    789
1     82
2     17
3      3
Name: count, dtype: int64

In [43]:
df_data = df.groupby(["cluster_group"]).mean()

In [44]:
df_data

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
cluster_group,,,,,,,,,
0,0.339670,2.471483,0.680608,0.505703,0.356147,18.737711,0.150824,0.095057,0.754119
1,0.731707,1.060976,0.390244,0.634146,0.463415,101.508839,0.451220,0.024390,0.500000
2,0.647059,1.000000,0.352941,0.882353,1.176471,238.187253,0.529412,0.000000,0.470588
3,1.000000,1.000000,0.666667,0.000000,0.333333,512.329200,1.000000,0.000000,0.000000

In [46]:
df.loc[df["cluster_group"] == 1].describe()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,cluster_group
count,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.000000,82.0
mean,0.731707,1.060976,0.390244,0.634146,0.463415,101.508839,0.451220,0.024390,0.500000,1.0
std,0.445797,0.240758,0.490807,0.598603,0.740289,27.501054,0.500677,0.155207,0.503077,0.0
min,0.000000,1.000000,0.000000,0.000000,0.000000,73.500000,0.000000,0.000000,0.000000,1.0
25%,0.000000,1.000000,0.000000,0.000000,0.000000,79.200000,0.000000,0.000000,0.000000,1.0
50%,1.000000,1.000000,0.000000,1.000000,0.000000,89.552100,0.000000,0.000000,0.500000,1.0
75%,1.000000,1.000000,1.000000,1.000000,1.000000,120.000000,1.000000,0.000000,1.000000,1.0
max,1.000000,2.000000,1.000000,2.000000,2.000000,164.866700,1.000000,1.000000,1.000000,1.0